program: opt_task
project: inverse-learned-sss
method: random
metric:
  goal: minimize
  name: test/hausdorff_distance
parameters:
  debug:
    values: [False]
  isSweep:
    values: [True]
  spp:
    values: [8]
  n_crops:
    values: [2]
  sppse:
    values: [0]
  sppe:
    values: [0,4]
  mesh_lr:
    values: [0.0005,] # 0.0005 for rough geometry
  n_remesh:
    values: [500]
  scene:
    values: [
    # 'dragon1','dragon2',
    # 'gargoyle1','gargoyle2',
    'dragon1','dragon3',
    'gargoyle1','gargoyle3',
    #   'croissant1','croissant3',
    # 'maneki5','maneki8',
    # 'maneki6','maneki10',
    # 'torus1','torus3'
    ]
  laplacian: 
    values: [30,50]
command:
- ./exp4_learn.sh
- maneki1