
program: train.py
project: pg2024_rebuttal_prb
method: grid
metric:
  goal: minimize
  name: test/rmse_sig
parameters:
  debug:
    values: [False]
  sweep_num:
    values: [0, 1, 2, 3, 4, 5, 6,]
  spp:
    values: [8,16,32,]
    # values: [8,16,32,64]
  scene:
    values: [
      # 'croissant1',
      'duck',
      'maneki1',
      'gargoyle1',
      'botijo3',
      # 'botijo2',
      'maneki5',
      'head1',
    ]
command:
- bash
- ./related/train.sh
- head1