program: opt_task
project: inverse-learned-sss
method: random
metric:
  goal: minimize
  name: test/hausdorff_distance
parameters:
  debug:
    values: False
  isSweep:
    values: True
  spp:
    values: [4,8]
  n_crops:
    values: [1,2]
  sppse:
    values: [0,4]
  sppe:
    values: [0,4]
  mesh_lr:
    values: [0.001, 0.0005]
command:
- ./learn_all.sh
- maneki1